### ISSUE TITLE
Merge PDF 1.5 not working.

### ISSUE THREAD

**Issue by ewallteam** [myokyawhtun/PDFMerger#41]
Hi,
I am using PDF version 1.5. Unable to merge them, and got the below error.

Fatal error: Uncaught Exception: TCPDF_PARSER ERROR: decodeFilterFlateDecode: invalid code in /var/www/html/ /PDFMerger/tcpdf/include/tcpdf_filters.php:475 Stack trace: 
#0 /var/www/html/Optimization/PDFMerger/tcpdf/include/tcpdf_filters.php(360): PDFMerger\TCPDF_FILTERS::Error('decodeFilterFla...') 
#1 /var/www/html/Optimization/PDFMerger/tcpdf/include/tcpdf_filters.php(95): PDFMerger\TCPDF_FILTERS::decodeFilterFlateDecode('b\x8F\\\xBEW)ccQ\x0F\x06E\x83!j...') 
#2 /var/www/html/Optimization/PDFMerger/tcpdf/tcpdi_parser.php(1173): PDFMerger\TCPDF_FILTERS::decodeFilter('FlateDecode', 'b\x8F\\\xBEW)ccQ\x0F\x06E\x83!j...') 
#3 /var/www/html/Optimization/PDFMerger/tcpdf/tcpdi_parser.php(1061): PDFMerger\tcpdi_parser->decodeStream(Array, 'b\x8F\\\xBEW)ccQ\x0F\x06E\x83!j...') 
#4 /var/www/html/Optimization/PDFMerger/tcpdf/tcpdi_parser.php(1097): PDFMerger\tcpdi_parser->extractObjectStream(Array) 
#5 /var/www/html/Optimization/PDFMerger/tcpdf/tcpdi_parser.php(214): PDFMerger\tcpdi_parser->findObjectOffsets() 
#6 /var/www/htm in /var/www/html/Optimization/PDFMerger/tcpdf/include/tcpdf_filters.php on line 475

**Comment by peterwesterlund** [comment]
I'll get exactly the same error.
