### ISSUE TITLE
FATAL ERROR in tcpdi_parser.php - Includes fix detail.

### ISSUE THREAD

**Issue by SpencerPlanton** [myokyawhtun/PDFMerger#53]
Was recieving the following error on 'some' merge requests:

Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, bool given in C:\MyPath\www\PDFMerger\tcpdf\tcpdi_parser.php:503 Stack trace: #0 C:\MyPath\www\PDFMerger\tcpdf\tcpdi_parser.php(373): tcpdi_parser->decodeXrefStream() #1 C:\MyPath\www\\PDFMerger\tcpdf\tcpdi_parser.php(212): tcpdi_parser->getXrefData() #2 C:\MyPath\www\\PDFMerger\tcpdf\tcpdi.php(121): tcpdi_parser->__construct() #3 C:\MyPath\www\\PDFMerger\tcpdf\tcpdi.php(88): TCPDI->_getPdfParser() #4 C:\MyPath\www\\PDFMerger\PDFMerger.php(97): TCPDI->setSourceFile() #5 C:\MyPath\www\\offline downloads\download-DL100.php(75): PDFMerger\PDFMerger->merge() #6 {main} thrown in C:\MyPath\www\\PDFMerger\tcpdf\tcpdi_parser.php on line 503

Line 503 is:
            } elseif (($key == '/Index') AND ($v[0] == PDF_TYPE_ARRAY AND count($v[1] >= 2))) {
            
Changed to:
            } elseif (($key == '/Index') AND ($v[0] == PDF_TYPE_ARRAY AND count($v[1]) >= 2)) {

Please verify this change and update the release accordingly if fit for purpose. :)

**Comment by Courtsilius** [comment]
Thank you so much! This helped me since I had issues with bigger PDF files (more than 100 pages).

Additionally to that I added a check before the "switch ($predictor) {" on line 375, basically just

if(Count($row)<=$i){continue;}


somewhat hacky, but it works in my case, so leaving this just in case someone else might stumble on this c:

**Comment by Manitnelav** [comment]
Thank you so much!! You saved my day!

**Comment by SpencerPlanton** [comment]
No Worries. 
This could do with being addressed in the code and made part of a release?

**Comment by SpencerPlanton** [comment]
No problem, glad it helped you.
Spencer
